vim.g.mapleader = " "
local set = vim.opt
-- set.endofline = true
set.pumblend = 0
set.backup = false
set.mouse = ""
set.swapfile = false
set.clipboard:append("unnamedplus")
set.number = true
-- set.relativenumber = true
set.termguicolors = true
set.updatetime = 100
set.tabstop = 2
set.ts = 2
set.sw = 2
set.sts = 2
set.expandtab = true
set.smarttab = true
set.splitbelow = true
set.splitright = true
set.regexpengine = 1
set.synmaxcol = 200
set.directory = "~/.config/nvim/tmp//"
set.title = true
set.list = true
set.listchars = "tab:  ,trail:×,nbsp:.,extends:#"
set.fillchars = "eob: ,fold: ,vert: "
set.encoding = "utf-8"
set.belloff = "all"
set.hidden = true
set.ttimeoutlen = 0
set.ttyfast = true
set.cmdheight = 2
set.autoindent = true
set.smartindent = true
set.cindent = true
set.incsearch = true
set.hlsearch = true
set.autoread = true
set.wildmenu = true
set.ignorecase = true
set.smartcase = true
set.linebreak = true
set.backspace = "indent,eol,start"
set.colorcolumn = "80"
set.cursorline = true
set.updatetime = 250
set.signcolumn = "yes"
set.splitright = true
set.splitbelow = true
set.swapfile = false
set.background = "dark"
set.spell = true
vim.api.nvim_command("set nomodeline")
vim.api.nvim_command("set noexpandtab")
vim.api.nvim_command("set nofoldenable")
vim.api.nvim_command("set completeopt=preview")
-- vim.opt.fileformats = "unix,dos,mac,txt"
